CREATE TABLE DEPT (
DEPTNO INT PRIMARY KEY,
DNAME VARCHAR(50),
LOC VARCHAR(50)
);

CREATE TABLE EMP (
 EMPNO INT PRIMARY KEY,
 ENAME VARCHAR(50),
 JOB CHAR(20),
 MGR INT,
 HIREDATE DATE,
 SAL INT,
 COMM INT,
 DEPTNO INT,
 FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO));


SELECT * FROM dept;

